### ISSUE TITLE
Club House map images (new) are available from Ubi

### ISSUE THREAD

**Issue by jonathanymkim** [purechaose/r6maps#10]
Just checked at https://rainbow6.ubisoft.com/siege/en-us/game-info/maps/clubhouse.aspx and the 2nd floor blueprints include the new "construction" section between cash and bedroom. I believe these are the files you need to update Club.

Cheers.

**Comment by purechaose** [comment]
Awesome, thank you so much! I'll get this added as soon as I can, hopefully by the end of Sunday.

**Comment by ghost** [comment]
Thanks for your work on this project! I've been looking for this forever

**Comment by purechaose** [comment]
Update: New Club is now on the fork's github pages
