### ISSUE TITLE
This should be pulled back to main branch

### ISSUE THREAD

**Issue by andwan0** [purechaose/r6maps#8]
This appears to be latest/active.. .how can we view this?

**Comment by purechaose** [comment]
You view the built version at https://purechaose.github.io/r6maps (and this link will automatically be kept up to date with the latest version of my fork).
You can also download a copy for offline use via the [releases](https://github.com/purechaose/r6maps/releases). I do my best to keep this up to date with the master branch, but may be missing small bug fixes or small features.
Unfortunately, capajon has not been active in r6maps for almost 2 years now, so I'm not optimistic that my fork will ever be pulled into his repo or r6maps.com. 

Edit: I saw you wanted a tutorial on how to update/add maps, and I've made a [wiki](https://github.com/purechaose/r6maps/wiki) on this repo just for that. If you want to try your hand at it, go ahead! I can always help, and feedback on the wiki.
